version: "3.8"

services:
  global-api:
    build: "./global-api/"
    ports:
      - "8080:8080"
    container_name: global-api
    command: ["./wait-for-it.sh", "rabbitmq:5672", "java","-jar","/app.jar"]
    depends_on:
      - db

  kitty-service:
    build: "./kitty-service/"
    ports:
      - "8082:8080"
    container_name: kitty-service
    command: ["./wait-for-it.sh", "db:5432", "java","-jar","/app.jar"]
    depends_on:
      - db

  person-service:
    build: "./person-service/"
    ports:
      - "8081:8080"
    container_name: person-service
    command: ["./wait-for-it.sh", "db:5432", "java","-jar","/app.jar"]
    depends_on:
      - db

  db:
    image: "postgres:14.2"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=KotikiJava

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"